repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.10
  hooks:
    - id: ruff
      args: [ --fix ]
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
