name: Lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
      - uses: psf/black@stable