name: Run Python tests

on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - main

# Don't run duplicates - eg. if pushing to an open PR
concurrency:
  group: ${{ github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: pip install -e .[tests] pytest-md
      - name: Run tests
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: false
          job-summary: true
      - name: Report to coveralls
        uses: coverallsapp/github-action@v2
        with:
          flag-name: run-${{ join(matrix.*, '-') }}
          parallel: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  coverage:
    name: Report coverage
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: test
    steps:
      - name: Complete Coveralls report
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true

